version: 0.2

env:
  secrets-manager:
    db_password: "java-secrets:password"
    db_username: "java-secrets:username"
    db_host: "java-secrets:host"
    db_port: "java-secrets:port"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y mysql-server

  pre_build:
    commands:
      - echo connection to database 
      - mysql -h ${db_host} -P ${db_port} -u ${db_username} -p ${db_password}

  build:
    commands:
      - echo Compiling the application...
      - mvn clean compile
      - echo Running tests...
      - mvn test
  post_build:
    commands:
      - echo Packaging artifacts...
      - mvn package

artifacts:
  files:
    - target/*.jar